##Given Code

##Building a Neural Network with Feed-forward

In [5]:
import numpy as np

# -------------------------------
# Sigmoid activation function
# -------------------------------
def sigmoid(x):
    """Sigmoid activation"""
    return 1 / (1 + np.exp(-x))

# -------------------------------
# Initialize network
# -------------------------------
np.random.seed(42)

input_dim = 1
hidden_dim = 3
output_dim = 1

# Initialize weights and biases
W1 = np.random.randn(hidden_dim, input_dim)
b1 = np.zeros((hidden_dim, 1))
W2 = np.random.randn(output_dim, hidden_dim)
b2 = np.zeros((output_dim, 1))

# -------------------------------
# Forward pass
# -------------------------------
def forward(X):
    Z1 = np.dot(W1, X) + b1
    A1 = sigmoid(Z1)          # sigmoid activation in hidden layer
    Z2 = np.dot(W2, A1) + b2
    A2 = sigmoid(Z2)          # sigmoid activation in output layer
    return Z1, A1, Z2, A2

# Example input
X = np.array([[0.5]])

Z1, A1, Z2, A2 = forward(X)

print("Input X:", X)
print("Z1 =", Z1.ravel())
print("A1 =", A1.ravel())
print("Z2 =", Z2.ravel())
print("A2 (output) =", A2.ravel())

Input X: [[0.5]]
Z1 = [ 0.24835708 -0.06913215  0.32384427]
A1 = [0.56177208 0.48272384 0.58026084]
Z2 = [0.60670373]
A2 (output) = [0.64718851]


##Part(a) input vectors and output vectors

In [6]:
import numpy as np

# Reuse weights and biases from the previous cell
# W1, b1, W2, b2, and sigmoid function are already defined in the previous cell

X = np.array([[0.5]])

print("Input X:", X)

# Step 1: Calculate the weighted sum of inputs for the hidden layer (Z1)
print("\n--- Step 1: Calculate Z1 ---")
print("W1 =\n", W1)
print("X =\n", X)
print("b1 =\n", b1)
Z1 = np.dot(W1, X) + b1
print("Z1 = W1 * X + b1 =\n", Z1)

# Step 2: Apply the sigmoid activation function to the hidden layer output (A1)
print("\n--- Step 2: Calculate A1 ---")
print("Z1 =\n", Z1)
A1 = sigmoid(Z1)
print("A1 = sigmoid(Z1) =\n", A1)

# Step 3: Calculate the weighted sum of hidden layer outputs for the output layer (Z2)
print("\n--- Step 3: Calculate Z2 ---")
print("W2 =\n", W2)
print("A1 =\n", A1)
print("b2 =\n", b2)
Z2 = np.dot(W2, A1) + b2
print("Z2 = W2 * A1 + b2 =\n", Z2)

# Step 4: Apply the sigmoid activation function to the output layer output (A2)
print("\n--- Step 4: Calculate A2 (output) ---")
print("Z2 =\n", Z2)
A2 = sigmoid(Z2)
print("A2 (output) = sigmoid(Z2) =\n", A2)

Input X: [[0.5]]

--- Step 1: Calculate Z1 ---
W1 =
 [[ 0.49671415]
 [-0.1382643 ]
 [ 0.64768854]]
X =
 [[0.5]]
b1 =
 [[0.]
 [0.]
 [0.]]
Z1 = W1 * X + b1 =
 [[ 0.24835708]
 [-0.06913215]
 [ 0.32384427]]

--- Step 2: Calculate A1 ---
Z1 =
 [[ 0.24835708]
 [-0.06913215]
 [ 0.32384427]]
A1 = sigmoid(Z1) =
 [[0.56177208]
 [0.48272384]
 [0.58026084]]

--- Step 3: Calculate Z2 ---
W2 =
 [[ 1.52302986 -0.23415337 -0.23413696]]
A1 =
 [[0.56177208]
 [0.48272384]
 [0.58026084]]
b2 =
 [[0.]]
Z2 = W2 * A1 + b2 =
 [[0.60670373]]

--- Step 4: Calculate A2 (output) ---
Z2 =
 [[0.60670373]]
A2 (output) = sigmoid(Z2) =
 [[0.64718851]]


##Part(b) :  
(i) Number of hidden layers,
(ii) Number of units in the layers including input and output layer.


Here is the information about the network structure based on the code:

(i). Hidden layers: This network has **one** hidden layer.
(ii). Number of units in the layers:
*   Input layer: **1** unit (input_dim = 1)
*   Hidden layer: **3** units (hidden_dim = 3)
*   Output layer: **1** unit (output_dim = 1)

##extend this code to two hidden layers.

In [8]:
import numpy as np

# -------------------------------
# Sigmoid activation function
# -------------------------------
def sigmoid(x):
    """Sigmoid activation"""
    return 1 / (1 + np.exp(-x))

# -------------------------------
# Initialize network with two hidden layers
# -------------------------------
np.random.seed(42) # Using the same seed for reproducibility

input_dim = 1
hidden_dim1 = 3
hidden_dim2 = 2
output_dim = 1

# Initialize weights and biases
W1 = np.random.randn(hidden_dim1, input_dim)
b1 = np.zeros((hidden_dim1, 1))
W2 = np.random.randn(hidden_dim2, hidden_dim1)
b2 = np.zeros((hidden_dim2, 1))
W3 = np.random.randn(output_dim, hidden_dim2)
b3 = np.zeros((output_dim, 1))

# -------------------------------
# Forward pass for a network with two hidden layers
# -------------------------------
def forward_two_hidden(X_input):

    Z1 = np.dot(W1, X_input) + b1
    A1 = sigmoid(Z1) # Activation of the first hidden layer
    Z2 = np.dot(W2, A1) + b2
    A2 = sigmoid(Z2) # Activation of the second hidden layer
    Z3 = np.dot(W3, A2) + b3
    Y_output = sigmoid(Z3) # Output layer activation

    return Z1, A1, Z2, A2, Z3, Y_output

# Example input
X_example = np.array([[0.5]])

Z1_val, A1_val, Z2_val, A2_val, Z3_val, Y_output_val = forward_two_hidden(X_example)

print("Input X:", X_example)
print("Z1 =", Z1_val.ravel())
print("A1 (Activation of Hidden Layer 1) =", A1_val.ravel())
print("Z2 =", Z2_val.ravel())
print("A2 (Activation of Hidden Layer 2) =", A2_val.ravel())
print("Z3 =", Z3_val.ravel())
print("Y (Output) =", Y_output_val.ravel())

Input X: [[0.5]]
Z1 = [ 0.24835708 -0.06913215  0.32384427]
A1 (Activation of Hidden Layer 1) = [0.56177208 0.48272384 0.58026084]
Z2 = [0.60670373 0.98519911]
A2 (Activation of Hidden Layer 2) = [0.64718851 0.72813861]
Z3 = [0.01370631]
Y (Output) = [0.50342652]
